version: "3.9"

services:
  inframind:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inframind-monitor
    restart: unless-stopped
    ports:
      - "8050:8050"
    environment:
      APP_ENV: production
      TZ: UTC
      ENABLE_AGENTLESS_WORKER: "1"
      WORKER_TICK_SEC: "2"
      WORKER_TIMEOUT_SEC: "2"
    volumes:
      - inframind_data:/app/data

volumes:
  inframind_data:
